# Generated by Django 5.1.3 on 2024-12-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0008_user_mobile_number'),
        ('teacher', '0011_alter_feedback_id_alter_reply_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist_Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='teacher.course')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student.playlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_playlist_title'),
        ),
    ]
