# Generated by Django 5.1.3 on 2024-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('avatar', models.CharField(default='fallback.webp', max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('pro', 'Pro')], default='student', max_length=20)),
                ('status', models.CharField(choices=[('member', 'Member'), ('pro', 'Pro')], default='member', max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
