# Generated by Django 5.1.3 on 2024-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.IntegerField()),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'otps',
            },
        ),
    ]
