# Generated by Django 5.1.3 on 2024-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=12, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
