# Generated by Django 5.1.3 on 2024-12-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mobile_number',
        ),
    ]
