# Generated by Django 5.1.3 on 2024-12-04 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_course_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='teacher.course'),
            preserve_default=False,
        ),
    ]
