# Generated by Django 5.1.3 on 2024-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_couponcode_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(default='$12', max_length=255),
            preserve_default=False,
        ),
    ]
