# Generated by Django 5.1.3 on 2024-12-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_mobile_number'),
        ('teacher', '0004_remove_course_price_currency_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
