# Generated by Django 5.1.3 on 2024-12-11 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_mobile_number'),
        ('teacher', '0006_coursepoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePurchasers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
