# Generated by Django 5.1.3 on 2024-12-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_coursepurchasers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepurchasers',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollements', to='teacher.course'),
        ),
    ]
